import { createClient } from "@/lib/supabase/server";
import { ManufacturingManager } from "@/components/manufacturing/ManufacturingManager";

export default async function ManufacturingPage({
  params,
}: PageProps<"/[companyId]/manufacturing">) {
  const { companyId } = await params;
  const supabase = await createClient();

  const [{ data: modules }, { data: boms }, { data: items }, { data: branches }, { data: godowns }] = await Promise.all([
    supabase.rpc("get_company_modules", { p_company_id: companyId }),
    supabase.rpc("get_boms", { p_company_id: companyId }),
    supabase
      .from("items")
      .select("id, name, uom, sale_rate")
      .eq("company_id", companyId)
      .eq("is_active", true)
      .eq("maintain_stock", true)
      .order("name"),
    supabase.from("branches").select("id, code, name").eq("company_id", companyId).eq("is_active", true),
    supabase.from("godowns").select("id, name, is_default").eq("company_id", companyId).eq("is_active", true),
  ]);

  const bomIds = (boms ?? []).map((b) => b.bom_id);
  const { data: components } =
    bomIds.length > 0
      ? await supabase
          .from("bom_components")
          .select("id, bom_id, component_item_id, quantity, items(name, uom)")
          .in("bom_id", bomIds)
          .order("line_order")
      : { data: [] };

  const componentRows = (components ?? []).map((c) => ({
    id: c.id,
    bom_id: c.bom_id,
    component_item_id: c.component_item_id,
    quantity: c.quantity,
    item_name: (c.items as unknown as { name: string; uom: string } | null)?.name ?? "",
    uom: (c.items as unknown as { name: string; uom: string } | null)?.uom ?? "",
  }));

  // bom_outputs is brand new in migration 0114 — types/database.types.ts
  // (owned by the integration pass, not regenerated by this task) doesn't
  // know about it yet, hence the disabled rule below. Purely a compile-time
  // typing gap; RLS and the runtime shape are both verified live.
  const { data: outputs } =
    bomIds.length > 0
      ? await supabase
          // eslint-disable-next-line @typescript-eslint/no-explicit-any -- see above
          .from("bom_outputs" as any)
          .select("id, bom_id, output_type, output_item_id, quantity, nrv_rate, items(name, uom)")
          .in("bom_id", bomIds)
          .order("line_order")
      : { data: [] as Record<string, unknown>[] };

  const outputRows = ((outputs ?? []) as unknown as Record<string, unknown>[]).map((o) => ({
    id: o.id as string,
    bom_id: o.bom_id as string,
    output_type: o.output_type as "by_product" | "scrap" | "co_product",
    output_item_id: o.output_item_id as string,
    quantity: o.quantity as number,
    nrv_rate: o.nrv_rate as number,
    item_name: (o.items as { name: string; uom: string } | null)?.name ?? "",
    uom: (o.items as { name: string; uom: string } | null)?.uom ?? "",
  }));

  const manufacturingOn = (modules ?? []).some((m) => m.code === "manufacturing" && m.active);

  return (
    <main className="mx-auto max-w-6xl px-6 py-10">
      <header className="mb-8">
        <h1 className="font-display text-2xl font-semibold tracking-tight text-ink">
          Manufacturing
        </h1>
        <p className="mt-1 text-sm text-ink-soft">
          One recipe per output item. A production run consumes every component at its
          current weighted-average rate and receives the finished item at that cost — an
          internal stock transformation, not a supply, so it posts no P&amp;L impact. A
          recipe can also declare by-products, scrap, or co-products it throws off — those
          now actually enter stock at a real valuation instead of the finished good silently
          absorbing their share of the cost.
        </p>
      </header>

      {!manufacturingOn ? (
        <p className="rounded-lg border border-dashed border-border-strong px-5 py-8 text-center text-sm text-ink-faint">
          Manufacturing and BOM is not active for this company. Turn it on in
          Settings → Modules to define recipes and record production.
        </p>
      ) : (
        <ManufacturingManager
          companyId={companyId}
          boms={(boms ?? []) as never}
          components={componentRows}
          outputs={outputRows}
          items={items ?? []}
          branches={branches ?? []}
          godowns={godowns ?? []}
        />
      )}
    </main>
  );
}
