import { createClient } from "@/lib/supabase/server";
import { SBOManager, type SBO } from "@/components/sbo/SBOManager";

export default async function SignificantBeneficialOwnersPage({
  params,
}: PageProps<"/[companyId]/significant-beneficial-owners">) {
  const { companyId } = await params;
  const supabase = await createClient();

  // significant_beneficial_owners is brand new in migration 0296 —
  // types/database.types.ts (owned by the integration pass, not
  // regenerated by this task) doesn't know about it yet, hence the
  // disabled rule below. Purely a compile-time typing gap; RLS and the
  // runtime shape are both verified live (see the structured report).
  const [{ data: companyRow }, { data: owners }] = await Promise.all([
    supabase.from("companies").select("entity_type").eq("id", companyId).single(),
    supabase
      // eslint-disable-next-line @typescript-eslint/no-explicit-any -- see above
      .from("significant_beneficial_owners" as any)
      .select(
        "id, individual_name, pan, interest_nature, held_through_entity_name, held_through_entity_type, qualifying_basis, percentage_held, date_became_sbo, date_ceased_sbo, ben1_received_date, ben2_filed_date, notes"
      )
      .eq("company_id", companyId)
      .order("date_ceased_sbo", { ascending: true, nullsFirst: true })
      .order("date_became_sbo", { ascending: true }),
  ]);

  const entityType = companyRow?.entity_type ?? null;
  const ownerRows = (owners ?? []) as unknown as SBO[];
  const currentCount = ownerRows.filter((o) => !o.date_ceased_sbo).length;

  return (
    <main className="mx-auto max-w-6xl px-6 py-10">
      <header className="mb-8">
        <h1 className="font-display text-2xl font-semibold tracking-tight text-ink">
          Significant Beneficial Owners
        </h1>
        <p className="mt-1.5 max-w-2xl text-sm text-ink-soft">
          The Form BEN-3 register Sec 90 Companies Act 2013 requires: individuals who cross a
          10% shares / voting-rights / dividend-right threshold, or exercise significant
          influence or control, WITHOUT their own name appearing on this company&rsquo;s
          Register of Members — because they hold through another body corporate, HUF,
          partnership or trust, or under an undisclosed nominee arrangement. This is the
          people-behind-the-members layer the Register of Members (Share capital screen) and
          the directors/KMP register both stop short of.
        </p>
        <p className="mt-1.5 text-sm text-ink-soft">
          <span className="font-semibold text-ink">{currentCount}</span> current SBO
          {currentCount === 1 ? "" : "s"} on record.
        </p>
      </header>

      <SBOManager companyId={companyId} owners={ownerRows} entityType={entityType} />

      <p className="mt-6 max-w-2xl text-xs text-ink-faint">
        This screen tracks who has declared Form BEN-1 and when this company filed Form BEN-2
        with the Registrar — it does not generate BEN-1/BEN-2/BEN-3/BEN-4, e-file BEN-2 with the
        MCA (no API access for that), or compute automatically whether any shareholding crosses
        the 10% threshold. Determining that requires knowing the cap table of the entity the
        individual holds through, which this app does not model. It also does not send a Form
        BEN-4 notice to someone suspected of an undeclared interest — that is a different act
        (probing for a declaration that has not arrived) from recording one that has.
      </p>
    </main>
  );
}
